#!/bin/sh
set -e

tedge refresh-bridges

# Automatically added by thin-edge.io
if [ $1 -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Initial installation
    /usr/lib/systemd/systemd-update-helper install-system-units tedge-modbus-plugin.service || :
fi
# End automatically added section
# Automatically added by thin-edge.io
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	if [ $1 -eq 2 ]; then
		_dh_action=restart
	else
		_dh_action=start
	fi
	systemctl $_dh_action tedge-modbus-plugin.service >/dev/null || true
fi
# End automatically added section