#!/bin/sh
set -e
# Automatically added by thin-edge.io
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by thin-edge.io
if [ $1 -ge 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Package upgrade, not uninstall
    /usr/lib/systemd/systemd-update-helper mark-restart-system-units tedge-modbus-plugin.service || :
fi

# End automatically added section

if [ "$1" = "0" ]; then
    tedge config remove c8y.smartrest.templates modbus
    tedge refresh-bridges
fi
