#!/bin/sh
set -e
# Automatically added by thin-edge.io
if [ $1 -eq 0 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Package removal, not upgrade
    /usr/lib/systemd/systemd-update-helper remove-system-units tedge-modbus-plugin.service || :
fi
# End automatically added section

# Remove (logic is normally added by dh_python3 helper)
if which pyclean3 >/dev/null 2>&1; then
    pyclean3 -p modbus_reader
else
    dpkg -L modbus_reader | grep \.py$ | while read -r file
    do
        rm -f "${file}"[co] >/dev/null
    done
fi
