#!/bin/sh

set -e

#DEBHELPER#

# Enable the service only if systemctl is available
if command -v systemctl >/dev/null; then
        systemctl start te-modbus-plugin.service
        systemctl enable te-modbus-plugin.service
fi