config/devices.toml etc/tedge/plugins/modbus/
config/modbus.toml etc/tedge/plugins/modbus/
operations/c8y_ModbusConfiguration/dist/c8y_ModbusConfiguration /etc/tedge/plugins/modbus/
operations/c8y_ModbusConfiguration/c8y_ModbusConfiguration  /etc/tedge/operations/c8y/
operations/c8y_ModbusDevice/dist/c8y_ModbusDevice /etc/tedge/plugins/modbus/
operations/c8y_ModbusDevice/c8y_ModbusDevice  /etc/tedge/operations/c8y/