[modbus]
pollinterval=2
loglevel="INFO"
#combinemeasurements=true # if not set equals false; combines all measurements of a device to reduce the number of created measurements in the cloud

[serial]
port="/dev/ttyRS485"
baudrate=9600
stopbits=2
parity="N"
databits=8

[thinedge]
mqtthost="127.0.0.1"
mqttport=1883